package com.telerikacademy.oop.wim.commands.enums;

public enum CommandType {

    // creations
    CREATEMEMBER,
    CREATETEAM,
    CREATEBOARD,
    CREATEBUG,
    CREATEFEEDBACK,
    CREATESTORY,

    //ADD
    ADDMEMBERTOTEAM,
    ADDCOMMENTTOBUG,
    ADDCOMMENTTOFEEDBACK,
    ADDCOMMENTTOSTORY,

    // Listing
    LISTALLTEAMS,
    LISTALLMEMBERS,
    LISTALLWORKITEMSFROMBOARD,
    LISTALLWORKITEMSFROMMEMBER,
    LISTMEMBERACTIVITY,
    LISTTEAMACTIVITY,
    LISTALLTEAMBOARDS,
    LISTALLTEAMMEMBERS,
    LISTBOARDACTIVITY,
    LISTALLBUGS,
    LISTALLSTORIES,
    LISTALLFEEDBACK,

    //FILTRATION AND SORT
    FILTERBYSTATUS,
    FILTERBYASSIGNEE,
    FILTERBYASSIGNEEANDSTATUS,
    SORTBYTITLE,
    SORTBYPRIORITY,
    SORTBYSEVERITY,
    SORTBYSIZE,
    SORTBYRATING,

    //CHANGES
    CHANGEBUGPRIORITY,
    CHANGEBUGSEVERITY,
    CHANGEBUGSTATUS,
    CHANGESTORYPRIORITY,
    CHANGESTORYSIZE,
    CHANGESTORYSTATUS,
    CHANGEFEEDBACKSTATUS,
    CHANGEFEEDBACKRATING,
    ASSIGNWORKITEMTOMEMBER,
    UNASSIGNWORKITEMFROMMEMBER,

}